site_name: InfoWorks

nav:
  - Home: index.md
  - SCRUM: 
    - User Story: SCRUM/userStory.md
    - Product Backlog: SCRUM/productBacklog.md
  - UML:
    - Casos e Usos: UML/casosUsos.md
    - Banco de Dados: UML/bancoDados.md
  - LGPD:
    - Termos de Usos: LGPD/termosUsos.md
    - Política de Privacidade: LGPD/politicaPrivacidade.md

theme:
  name: null
  custom_dir: 'cinder'
  language: pt
  logo: ./images/logo.png
  favicon: ./images/favicon.png
  palette:
    primary: blue